name: Deploy Devspade Zola to Pages
on:
  push:
    branches:
      - main  
    workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
      
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Explicitly tell it to use the gh-pages branch
          PAGES_BRANCH: gh-pages